# def init_additional_buildings_db ():
#     return {"Постоянное место жительства": {"zakazat-stroitelstvo-po-proektu-mini-kontejner-dlya-sadovogo-inventarya": (35000, 2), 
#                                             "zakazat-stroitelstvo-po-proektu-drovnica-s-kozyrkom": (47_900, 3),
#                                             "zakazat-stroitelstvo-po-proektu-xozblok-dlya-sadovoj-texniki": (106_200, 5),
#                                             "zakazat-stroitelstvo-po-proektu-mini-garazh-avtomobilnyj": (367_600, 17),
#                                             "zakazat-stroitelstvo-po-proektu-garazh-dlya-motocikla": (183_600, 14)},
#             "Место отдыха, 'Дача'": {"zakazat-stroitelstvo-po-proektu-banya-faxverk": (2_340_000, 44),
#                                      "zakazat-stroitelstvo-po-proektu-gloriya-1": (28_000_000, 300),
#                                      "zakazat-stroitelstvo-po-proektu-banya-bochka-volga": (187_300, 6),
#                                      "zakazat-stroitelstvo-po-proektu-banya-3": (369_000, 30),
#                                      "zakazat-stroitelstvo-po-proektu-banya-k-3x4": (689_105, 9)},
#             "Место работы": {"zakazat-stroitelstvo-po-proektu-avtomobilnyj-garazh-1": (220_000, 17),
#                              "zakazat-stroitelstvo-po-proektu-garazh-7m": (248_900,17),
#                              "zakazat-stroitelstvo-po-proektu-garazh-dlya-avtomobilya": (367_600, 17),
#                              "zakazat-stroitelstvo-po-proektu-sklad-dlya-xraneniya": (129_600, 12),
#                              "zakazat-stroitelstvo-po-proektu-kontejner-dlya-xraneniya-s-oknom": (100_400, 5)},
#             }

def init_additional_buildings_db ():
    return {"zakazat-stroitelstvo-po-proektu-mini-kontejner-dlya-sadovogo-inventarya": (35000, 2), 
            "zakazat-stroitelstvo-po-proektu-drovnica-s-kozyrkom": (47_900, 3),
            "zakazat-stroitelstvo-po-proektu-xozblok-dlya-sadovoj-texniki": (106_200, 5),
            "zakazat-stroitelstvo-po-proektu-mini-garazh-avtomobilnyj": (367_600, 17),
            "zakazat-stroitelstvo-po-proektu-garazh-dlya-motocikla": (183_600, 14),
            "zakazat-stroitelstvo-po-proektu-banya-faxverk": (2_340_000, 44),
            "zakazat-stroitelstvo-po-proektu-gloriya-1": (28_000_000, 300),
            "zakazat-stroitelstvo-po-proektu-banya-bochka-volga": (187_300, 6),
            "zakazat-stroitelstvo-po-proektu-banya-3": (369_000, 30),
            "zakazat-stroitelstvo-po-proektu-banya-k-3x4": (689_105, 9),
            "zakazat-stroitelstvo-po-proektu-avtomobilnyj-garazh-1": (220_000, 17),
            "zakazat-stroitelstvo-po-proektu-garazh-7m": (248_900,17),
            "zakazat-stroitelstvo-po-proektu-garazh-dlya-avtomobilya": (367_600, 17),
            "zakazat-stroitelstvo-po-proektu-sklad-dlya-xraneniya": (129_600, 12),
            "zakazat-stroitelstvo-po-proektu-kontejner-dlya-xraneniya-s-oknom": (100_400, 5),
            }

