# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: step_recomendation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18step_recomendation.proto\"\x80\x01\n\x0cStep1Request\x12\x11\n\thouseArea\x18\x01 \x01(\r\x12\x10\n\x08siteArea\x18\x02 \x01(\r\x12\x12\n\nfloorCount\x18\x03 \x01(\r\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x13\n\x0b\x62udgetFloor\x18\x05 \x01(\r\x12\x12\n\nbudgetCeil\x18\x06 \x01(\r\" \n\rStep1Response\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x14Recomendation_system\x12\x31\n\x0erecomend_step1\x12\r.Step1Request\x1a\x0e.Step1Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'step_recomendation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STEP1REQUEST']._serialized_start=29
  _globals['_STEP1REQUEST']._serialized_end=157
  _globals['_STEP1RESPONSE']._serialized_start=159
  _globals['_STEP1RESPONSE']._serialized_end=191
  _globals['_RECOMENDATION_SYSTEM']._serialized_start=193
  _globals['_RECOMENDATION_SYSTEM']._serialized_end=266
# @@protoc_insertion_point(module_scope)
